#!/usr/bin/env bash
# Usage: mk_all.sh [subdirectory]
#
# Examples:
#   ./scripts/mk_all.sh
#   ./scripts/mk_all.sh data/real
#
# Makes a ../src/$directory/all.lean importing all files inside $directory.
# If $directory is omitted, creates `../src/all.lean`.

cd "$( dirname "${BASH_SOURCE[0]}" )"/../src
if [[ $# = 1 ]]; then
  dir="$1"
else
  dir="."
fi

echo '-- This file was automatically generated by the script `scripts/mk_all.sh`' > "$dir"/all.lean
echo '-- This file will likely timeout in an editor. Use `leanproject build` to compile this file' >> "$dir"/all.lean

find "$dir" -name \*.lean -not -name all.lean \
  | sed 's,^\./,,;s,\.lean$,,;s,/,.,g;s,^,import ,' \
  | sort >> "$dir"/all.lean

printf "\n#lint_sphere" >> "$dir"/all.lean