name: Compile blueprint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Allow manual triggering of the workflow from the GitHub Actions interface

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages and modify PR labels
permissions:
  contents: read          # Read access to repository contents
  pages: write            # Write access to GitHub Pages
  id-token: write         # Write access to ID tokens

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y

      - name: Get cache
        run: ~/.elan/bin/lake exe cache get || true

      - name: Build project
        run: ~/.elan/bin/lake build SphereEversion

      - name: Cache API docs
        uses: actions/cache@v4
        with:
          path: |
            docbuild/.lake/build/doc/Aesop
            docbuild/.lake/build/doc/Batteries
            docbuild/.lake/build/doc/find
            docbuild/.lake/build/doc/Init
            docbuild/.lake/build/doc/Lake
            docbuild/.lake/build/doc/Lean
            docbuild/.lake/build/doc/Mathlib
            docbuild/.lake/build/doc/Std
          key: Docs-${{ hashFiles('lake-manifest.json') }}

      - name: Build blueprint and copy to `docs/blueprint`
        uses: xu-cheng/texlive-action@v2
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20231201
          run: |
            export PIP_BREAK_SYSTEM_PACKAGES=1
            apk update
            apk add --update make py3-pip git pkgconfig graphviz graphviz-dev gcc musl-dev
            git config --global --add safe.directory $GITHUB_WORKSPACE
            git config --global --add safe.directory `pwd`
            python3 -m venv env
            source env/bin/activate
            pip install --upgrade pip requests wheel
            pip install pygraphviz --global-option=build_ext --global-option="-L/usr/lib/graphviz/" --global-option="-R/usr/lib/graphviz/"
            pip install leanblueprint
            leanblueprint pdf
            mkdir docs
            cp blueprint/print/print.pdf docs/blueprint.pdf
            leanblueprint web
            cp -r blueprint/web docs/blueprint

      - name: Check declarations
        run: ~/.elan/bin/lake exe checkdecls blueprint/lean_decls

      - name: Build project API documentation
        run: scripts/build_docs.sh

      - name: Install pandoc
        if: github.event_name == 'push'
        run: |
          sudo apt update
          sudo apt install pandoc

      - name: Build webpage
        if: github.event_name == 'push'
        run: |
          cd docs_src
          pandoc -t html --mathjax -f markdown+tex_math_dollars+raw_tex index.md --template template.html -o ../docs/index.html
          cp *.css ../docs

      - name: Upload docs & blueprint artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: Make sure the cache works
      #   run: mv docs/docs .lake/build/doc
